import type { Metadata } from "next";
import "./globals.css";
import SiteNavigation from "./components/siteNavigation";
import SiteSearch from "./components/siteSearch";
import SiteFooter from "./components/siteFooter";
import { AntdRegistry } from "@ant-design/nextjs-registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SiteNavigation />
        <AntdRegistry>
          <SiteSearch />
        </AntdRegistry>
        <AntdRegistry>{children}</AntdRegistry>
        <SiteFooter />
      </body>
    </html>
  );
}
