import type { Metadata } from "next";
import "./globals.css";
import SiteNavigation from "./components/siteNavigation";
import SiteSearch from "./components/siteSearch";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SiteNavigation />
        <SiteSearch />
        {children}
      </body>
    </html>
  );
}
